import requests
import logging

logger = logging.getLogger("jardx")

def send_push_notification(push_token: str, title: str, body: str, data_payload: dict = None) -> bool:
    """
    Sends a push notification to a specific user's device using Expo Push Notification Service.
    
    :param push_token: The unique ExponentPushToken string generated by the client.
    :param title: The title header of the push alert.
    :param body: The text description of the push alert.
    :param data_payload: A dictionary of custom key-value pairs (e.g. {"screen": "/housedetails", "params": {"id": "123"}}).
    :return: True if the notification request was successfully dispatched to Expo, False otherwise.
    """
    if not push_token or not isinstance(push_token, str):
        logger.warning("Push notification ignored: No target push token supplied.")
        return False
        
    if not push_token.startswith("ExponentPushToken"):
        logger.warning(f"Push notification ignored: Invalid Expo token format '{push_token}'.")
        return False

    url = "https://exp.host/--/api/v2/push/send"
    headers = {
        "Content-Type": "application/json",
        "accept-encoding": "gzip, deflate",
        "accept": "application/json"
    }
    
    payload = {
        "to": push_token,
        "sound": "default",
        "title": title,
        "body": body,
        "data": data_payload or {}
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=10)
        response_json = response.json()
        
        if response.status_code == 200:
            # Expo sends a structured status response
            data = response_json.get("data", {})
            if isinstance(data, dict):
                status = data.get("status")
                if status == "error":
                    logger.error(f"Expo notification dispatch error: {data.get('message')}")
                    return False
            elif isinstance(data, list) and len(data) > 0:
                # Batch list response format
                status = data[0].get("status")
                if status == "error":
                    logger.error(f"Expo notification dispatch error: {data[0].get('message')}")
                    return False
                    
            logger.info(f"Push notification successfully dispatched to {push_token}")
            return True
        else:
            logger.error(f"Expo gateway returned status code {response.status_code}: {response.text}")
            return False
            
    except requests.RequestException as e:
        logger.error(f"HTTP request error sending push notification: {e}")
        return False
